//-------------MOVIES----------
export const GET_ALL_MOVIES_START = "GET_ALL_MOVIES_START"
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS"
export const GET_ALL_MOVIES_FAILURE = "GET_ALL_MOVIES_FAILURE"
//----SEARCH FILTER VALUE----
export const SET_FILTER_VALUE = "SET_FILTER_VALUE"