//-------------MOVIES----------
export const GET_ALL_MOVIES_START = "GET_ALL_MOVIES_START"
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS"
export const GET_ALL_MOVIES_FAILURE = "GET_ALL_MOVIES_FAILURE"
//----SEARCH FILTER VALUE----
export const SET_FILTER_VALUE = "SET_FILTER_VALUE"
//----SET NOMINATED MOVIE----
export const SET_NOMINATED_MOVIE_START = "SET_NOMINATED_MOVIE_START"
export const SET_NOMINATED_MOVIE_SUCCESS = "SET_NOMINATED_MOVIE_SUCCESS"
export const SET_NOMINATED_MOVIE_FAILURE = "SET_NOMINATED_MOVIE_FAILURE"
//----REMOVE NOMINATED MOVIE----
export const REMOVE_NOMINATED_MOVIE_START = "REMOVE_NOMINATED_MOVIE_START"
export const REMOVE_NOMINATED_MOVIE_SUCCESS = "REMOVE_NOMINATED_MOVIE_SUCCESS"
export const REMOVE_NOMINATED_MOVIE_FAILURE = "REMOVE_NOMINATED_MOVIE_FAILURE"
