//-------------MOVIES----------
export const GET_ALL_MOVIES_START = "GET_ALL_MOVIES_START"
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS"
export const GET_ALL_MOVIES_FAILURE = "GET_ALL_MOVIES_FAILURE"
//----SEARCH FILTER VALUE----
export const SET_FILTER_VALUE = "SET_FILTER_VALUE"
//----SET NOMINATED MOVIE----
export const SET_NOMINATED_MOVIE = "SET_NOMINATED_MOVIE_START"
//----REMOVE NOMINATED MOVIE----
export const REMOVE_NOMINATED_MOVIE = "REMOVE_NOMINATED_MOVIE"
